# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: AJ's Aesthetic Journeys
description: 
baseurl: "/"
url: "https://ajsaestheticjourneys.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: "/"
    - name: About
      slug: "/work"
    - name: A&E Dashboard
      slug: "/emergencyroom"
    - name: HCAHPS Dashboard
      slug: "/patientsatisfaction"
    - name: Vaccination Dashboard
      slug: "/vaccinationmetrics"

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: albertqpome@gmail.com
  follow:
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/al-%D9%8B-b130b2300/
    - type: github
      name: GitHub
      link: https://ajsaestheticjourneys.github.io/

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
